baseURL = "https://www.phenorobdaa.de/"
languageCode = "en-us"
title = "My New Site"

[menu]
  [[menu.main]]
    identifier = "members"
    name = "Members"
    url = "/members/"

[directories]
contentDir = "content"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

pygmentsCodeFences = true
