name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          HUGO_VERSION=0.115.3  # Replace with your Hugo version
          HUGO_BINARY=hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}
          sudo dpkg -i ${HUGO_BINARY}
          hugo version

      - name: Build
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Change this if you're using a different branch
          publish_dir: ./public  # Change this if your Hugo output directory is different
