name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.3'  # Replace with your Hugo version

      - name: Build
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Change this if you're using a different branch
          publish_dir: ./public  # Change this if your Hugo output directory is different
